### ISSUE TITLE
Optimize font weight in font shorthand?

### ISSUE THREAD

**Issue by alebelcor** [ben-eb/postcss-minify-font-weight#1]
Would it be possible to optimize the weight values when using the `font` shorthand?

Given this:

```css
.test {
  font: bold 16px Arial;
}
```

The output should be:

```css
.test {
  font: 700 16px Arial;
}
```
